version: '3'
services:
  app:
    image: kbdom
    container_name: kbdom
    build:
      context: .
      dockerfile: .docker/php-apache/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=kbdom
      - DB_USERNAME=kbdom_user
      - DB_PASSWORD=secret
      - QUEUE_CONNECTION=database
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_kbdom
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: kbdom
      MYSQL_USER: kbdom_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  migration:
    image: kbdom:latest
    volumes:
      - .:/var/www/app
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=kbdom
      - DB_USERNAME=kbdom_user
      - DB_PASSWORD=secret
    command: ["sh", "-c", "/./wait-for-it/wait-for-it.sh mysql:3306 -t 60 -- composer install && php /var/www/app/artisan migrate && php /var/www/app/artisan db:seed"]
    links:
      - mysql
    depends_on:
      - app
      - mysql
